backend:
  image: adobe-code-challenge-php
  tag: latest
  port: 8080
  pullPolicy: IfNotPresent

frontend:
  image: adobe-code-challenge-frontend
  tag: latest
  port: 80
  pullPolicy: IfNotPresent

postgres:
  user: postgres
  password: postgres
  db: adobe

redis:
  port: 6379
